### ISSUE TITLE
Add a metric which shows the age of the oldest event in the queue

### ISSUE THREAD

**Issue by boreq** [planetary-social/nos-notification-service-go#16]
Right now we only have a metric which tracks the number of events in the queue. This means that events which are stuck could slip under the radar.

I believe we could easily add this to https://github.com/ThreeDotsLabs/watermill-firestore by changing the [subscriber](https://github.com/ThreeDotsLabs/watermill-firestore/blob/master/pkg/firestore/subscriber.go).

**Comment by boreq** [comment]
I attempted to do this but it is not obvious to me how to add a creation timestamp to those docs while maintaining full backward compatibility in watermill-firestore.

**Comment by boreq** [comment]
It is also annoying to add this in our service because most of the stuff we need from the subscriber is private. That means that we will be copying a lot of code.

**Comment by mplorentz** [comment]
Given that the queue length is always 0 let's just set up an alert if it goes above zero for a while.

**Comment by boreq** [comment]
Replaced with https://github.com/planetary-social/infrastructure/issues/67
