### ISSUE TITLE
Push Notification Service is down

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/nos-notification-service-go#53]
This service is crashing every few minutes and is no longer sending any push notifications according to the [dashboard](https://grafana.planetary.tools/d/d2f0e817-0bd6-4657-a405-60ed79c29e67/notification-service?orgId=1&refresh=30s&from=now-7d&to=now). We need to figure out why and get it running again.

**Comment by dcadenas** [comment]
This was solved by https://github.com/planetary-social/nos-notification-service-go/pull/54
This fixed the crash, but the service itself was failing because of a certificate issue that is solved through https://github.com/planetary-social/ansible-scripts/pull/113

**Comment by dcadenas** [comment]
More info here https://planetary-app.slack.com/archives/C056EQP6JK1/p1722286150879099?thread_ts=1722270232.720249&cid=C056EQP6JK1
